---
- hosts: all
  roles:
  - { role: basic,
      tags: basic }

  - { role: docker,
      tags: docker }

  - { role: kubeadm,
      tags: kubeadm }
- hosts: master
  roles:
  - { role: k8s, 
      tags: k8s  }                    #when: k8s_version.startswith('1.10.')}

  - { role: calico,
      tags: calico }
- hosts: 
    - master
    - node
  roles:
  - { role: node,
      tags: node }
