- name: 添加阿里云K8S源
  copy: 
    src: files/kubernetes.repo 
    dest: /etc/yum.repos.d/kubernetes.repo
- name: 安装kubeadm{{k8s_version}},kubectl{{k8s_version}},kubelet{{k8s_version}}
  yum:  name={{item}}-{{k8s_version}}-0.x86_64 state=present
  with_items:
        - kubeadm
        - kubectl
        - kubelet


