---
- name: 基础软件安装
  yum: name={{item}} state=present
  with_items:
     - gcc
     - gcc-c++
     - wget
     - lrzsz
     - telnet
     - net-tools
     - epel*
     - vim
     - unzip
     - ntpdate
     - chrony
     - yum-utils
     - device-mapper-persistent-data
     - conntrack-tools
     - libseccomp
     - libtool-ltdl
- name: 关闭防火墙
  service: name=firewalld state=stopped enabled=no

- name: 设置时区
  shell: timedatectl set-timezone Asia/Shanghai

- name: 开启chrony
  service: name=chronyd state=started enabled=yes

- name: ntp同步
  shell: chronyc sources


- name: 关闭selinux
  shell: setenforce 0
#  shell: sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g" /etc/sysconfig/selinux && setenforce 0 && sed -i "s/^SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config   && sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/sysconfig/selinux  && sed -i "s/^SELINUX=permissive/SELINUX=disabled/g" /etc/selinux/config   && setenforce  0
  ignore_errors: yes
- name: 修改seliunx文件
  selinux: state=disabled

- name: 关闭swap
  shell: swapoff -a

- name: 同步k8s.conf
  copy:
   src: files/k8s.conf 
   dest: /etc/sysctl.d/k8s.conf

- name: 加载k8s.conf配置文件
  shell:  modprobe br_netfilter && sysctl -p /etc/sysctl.d/k8s.conf


- name: 同步ipvs.modules配置文件
  copy: 
   src: files/ipvs.modules
   dest: /etc/sysconfig/modules/ipvs.modules
   mode: 0755
  
- name: 执行ipvs.modules脚本
  shell: bash /etc/sysconfig/modules/ipvs.modules


- name: 安装ipvs
  yum: name={{item}} state=present
  with_items:
      - ipset
      - ipvsadm
