---
- name: kubeadm  token
  shell: kubeadm token create --print-join-command
  register: k8s_token
  when: inventory_hostname in groups['master']
- name: 设置变量k8s_token为set_fact
  set_fact: k8s_token={{ k8s_token.stdout }}
  ignore_errors: true
  when: inventory_hostname in groups['master']
- name: 验证是否计算节点
  shell: netstat -lntp|grep 10256
  register: k8s_node
  ignore_errors: true
- name: add node to k8s cluster
  shell: echo '' |  {{ hostvars[groups['master'][0]]['k8s_token'] }}
  when: inventory_hostname in groups['node'] and k8s_node.rc != 0
 # when:  order  is undefined
 
