---
- name: 安装[yum-utils,device-mapper-persistent-data,lvm2] 
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - yum-utils 
      - device-mapper-persistent-data 
      - lvm2
- name: 添加docker源
  shell: yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
- name: 建立缓存
  shell: yum makecache fast
- name: 安装docker
  #shell: yum -y install "{{ docker_version }}"
  yum: name={{ docker_version }} state=present
- name: 配置docker加速
  copy:
   src: files/daemon.json
   dest: /etc/docker/daemon.json
  notify:
   restrt docker
  
- name: 设置docker自动启动
  service: 
    name: docker 
    state: started 
    enabled: yes  
    daemon_reload: yes
